// Welcome to DAX query view! Learn more about DAX queries at https://aka.ms/dax-queries.
// Right-click on tables, columns, or measures in the data pane to access quick queries, or ask Copilot for help writing DAX.

// Select "Run" to try this sample DAX query.
EVALUATE
TOPN(
    12,
    FILTER(
        FactProductPerformance,
        FactProductPerformance[Year] = 1986  && FactProductPerformance[Metric Type] = "Monthly Return" && FactProductPerformance[Firm] = "Firm A"  && FactProductPerformance[Unified Product Name] = "Firm A - Equity"
    ),
    FactProductPerformance[Date], DESC
)
